spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
jwt:
  key:
  access-token-expiration-minutes: 10
  refresh-token-expiration-minutes: 300
#config:
#  domain: ${AWS_S3_ENDPOINT}