spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_MAIL_ID}
    password: ${GOOGLE_MAIL_PW}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      repositories:
        enabled: false
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        format_sql: true
        default_batch_fetch_size: 500
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_OAUTH_CLIENT_ID}
            clientSecret: ${GOOGLE_OAUTH_CLIENT_PW}
            scope:
              - email
              - profile
#          kakao:
#            client-id: 12724799959adf08b6b792ce11d9b465
#            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
#            client-authentication-method: POST
#            authorization-grant-type: authorization_code
#            scope: profile_nickname, profile_image, account_email, gender
#            client-name: Kakao
#        provider:
#          kakao:
#            authorization_uri: https://kauth.kakao.com/oauth/authorize
#            token_uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user_name_attribute: id
logging:
  level:
    org:
      springframework:
        orm:
jwt:
  key: partypeople5437895438023498342098039248230932580325809
  access-token-expiration-minutes: 10
  refresh-token-expiration-minutes: 300
